import { solveCaptcha } from './login'
import { test, expect } from '@playwright/test'
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { X509Certificate } from 'node:crypto'
import { tmpdir } from 'node:os'
import { join, resolve, dirname, basename } from 'node:path'

function personalCertificate() {
  const root = resolve(tmpdir()); const directory = mkdtempSync(join(root, 'utaped-signing-'))
  if (dirname(resolve(directory)) !== root || !basename(directory).startsWith('utaped-signing-')) throw new Error('Invalid test fixture directory')
  const key = join(directory, 'key.pem'); const certificate = join(directory, 'public.pem'); const container = join(directory, 'certificate.p12')
  const password = 'E2e-only-signing-password'
  try {
    const config = join(directory, 'openssl.cnf')
    writeFileSync(config, '[req]\ndistinguished_name=dn\n[dn]\n')
    execFileSync('openssl', ['req', '-config', config, '-x509', '-newkey', 'rsa:2048', '-nodes', '-keyout', key, '-out', certificate, '-days', '1', '-subj', '/CN=E2E Personal signer', '-addext', 'basicConstraints=critical,CA:FALSE', '-addext', 'keyUsage=critical,digitalSignature'], { stdio: 'ignore' })
    execFileSync('openssl', ['pkcs12', '-export', '-inkey', key, '-in', certificate, '-out', container, '-passout', 'pass:' + password], { stdio: 'ignore' })
    return { buffer: readFileSync(container), fingerprint: new X509Certificate(readFileSync(certificate)).fingerprint256.replaceAll(':', '').toLowerCase(), password }
  } finally { rmSync(directory, { recursive: true, force: true }) }
}

// This file is generated locally for the isolated validation stack, never committed.
const environment = Object.fromEntries(readFileSync('../.env.e2e', 'utf8').split(/\r?\n/).filter(line => line.includes('=')).map(line => {
  const index = line.indexOf('='); return [line.slice(0,index),line.slice(index+1)]
}))
const adminPassword = 'E2e-only-admin-password-2026'
const userPassword = 'E2e-only-user-password-2026'

function annexPdf() {
  const stream = 'BT /F1 12 Tf 60 760 Td (E2E original annex) Tj ET'
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>', '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>', `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`]
  let text = '%PDF-1.4\n'; const offsets = [0]
  objects.forEach((object, i) => { offsets.push(Buffer.byteLength(text)); text += `${i + 1} 0 obj\n${object}\nendobj\n` })
  // Exceed Nginx's default 1 MB to exercise the configured upload boundary.
  text += '%' + 'x'.repeat(1100000) + '\n'
  const start = Buffer.byteLength(text)
  text += 'xref\n0 6\n0000000000 65535 f \n' + offsets.slice(1).map(n => String(n).padStart(10, '0') + ' 00000 n \n').join('')
  text += `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF\n`
  return Buffer.from(text)
}

test('local identity, administration, context isolation, recovery and logout', async ({ page, request }) => {
  test.setTimeout(180000)
  await expect.poll(async () => {
    try { return (await request.get((process.env.E2E_API_URL || 'http://127.0.0.1:18080') + '/actuator/health')).status() } catch { return 0 }
  }, { timeout: 30000 }).toBe(200)
  const suffix = Date.now().toString()
  const email = `e2e-${suffix}@example.invalid`
  const displayName = `Usuario E2E ${suffix}`
  const group = `Grupo de prueba ${suffix}`
  const certificate = personalCertificate()
  await page.goto('/')
  await page.getByRole('textbox', { name: 'Usuario', exact: true }).fill(environment.BOOTSTRAP_ADMIN_EMAIL)
  await page.getByLabel('Contraseña', { exact: true }).fill(environment.BOOTSTRAP_ADMIN_PASSWORD)
  await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect.poll(async () => await page.getByRole('alert').isVisible() || await page.getByRole('button', { name: 'Cerrar sesión' }).isVisible()).toBeTruthy()
  // Re-running the isolated stack can retain the first changed administrator password.
  if (await page.getByRole('alert').isVisible()) {
    await page.getByLabel('Contraseña', { exact: true }).fill(adminPassword)
    await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  }
  await expect(page.getByRole('button', { name: 'Cerrar sesión' })).toBeVisible()
  if (await page.getByRole('heading', { name: 'Acceso temporal' }).isVisible()) {
    await page.getByLabel('Contraseña actual').fill(environment.BOOTSTRAP_ADMIN_PASSWORD)
    await page.getByLabel('Nueva contraseña', { exact: true }).fill(adminPassword)
    await page.getByLabel('Confirmar contraseña').fill(adminPassword)
    await page.getByRole('button', { name: 'Guardar contraseña' }).click()
    await expect(page.getByRole('heading', { name: 'Iniciar sesión' })).toBeVisible()
    await page.getByRole('textbox', { name: 'Usuario', exact: true }).fill(environment.BOOTSTRAP_ADMIN_EMAIL)
    await page.getByLabel('Contraseña', { exact: true }).fill(adminPassword)
    await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  }
  await page.getByRole('button', { name: 'Administración', exact: true }).click()
  await page.getByLabel('Nombres', { exact: true }).fill('Usuario E2E')
  await page.getByLabel('Apellidos', { exact: true }).fill(suffix)
  await page.getByLabel('Correo', { exact: true }).fill(email)
  await page.getByLabel('Contraseña temporal').fill('E2e-only-temporary-password')
  await page.getByRole('button', { name: 'Crear usuario', exact: true }).click()
  await expect(page.getByRole('cell', { name: email, exact: true })).toBeVisible()
  await page.getByLabel('Nombre del grupo').fill(group)
  await page.getByRole('button', { name: 'Crear grupo', exact: true }).click()
  await expect(page.getByLabel('Grupo', { exact: true })).toContainText(group)
  await page.getByLabel('Grupo', { exact: true }).selectOption({ label: group })
  await page.getByLabel('Usuario', { exact: true }).selectOption({ label: displayName })
  await page.getByRole('button', { name: 'Asignar integrante' }).click()
  await expect(page.getByRole('status')).toHaveText('Cambios guardados.')
  await page.getByLabel('Nombre del período').fill(`Período ${suffix}`)
  for (const [label,date] of [['Inicio del período','2026-07-01'],['Fin del período','2026-12-31'],['Inicio de elaboración',new Date(Date.now()-86400000).toISOString().slice(0,10)],['Fin de elaboración',new Date(Date.now()+86400000).toISOString().slice(0,10)],['Inicio de revisión','2026-08-01'],['Fin de revisión','2026-08-31']]) await page.getByLabel(label).fill(date)
  await page.getByRole('button', { name: 'Crear período', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Cambios guardados.')
  await page.getByLabel('Denominación del catálogo').fill('Recurso E2E ' + suffix)
  await page.getByRole('button', { name: 'Crear elemento', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Editar elemento Recurso E2E ' + suffix, exact: true })).toBeVisible()
  await page.getByLabel('Tipo de catálogo').selectOption('MEANS')
  await page.getByLabel('Denominación del catálogo').fill('Medio E2E ' + suffix)
  await page.getByRole('button', { name: 'Crear elemento', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Editar elemento Medio E2E ' + suffix, exact: true })).toBeVisible()
  await page.getByLabel('Grupo del catálogo').selectOption({ label: group })
  await page.getByLabel('Título de actividad del catálogo').fill('Actividad obligatoria E2E ' + suffix)
  await page.getByLabel('Obligatoria para este grupo').check()
  await page.getByRole('button', { name: 'Crear actividad del catálogo', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Editar actividad Actividad obligatoria E2E ' + suffix, exact: true })).toBeVisible()
  await page.getByLabel('Denominación colectiva del grupo').fill('Integrantes del grupo E2E')
  await page.getByRole('button', { name: 'Guardar denominación colectiva', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Configuración de planificación guardada.' })).toBeVisible()
  const certificateAdmin = page.getByRole('region', { name: 'Vinculación de certificados', exact: true })
  await certificateAdmin.getByLabel('Buscar firmante', { exact: true }).fill(email)
  await expect(certificateAdmin.getByLabel('Cuenta del firmante')).toContainText(email)
  await certificateAdmin.getByLabel('Cuenta del firmante').selectOption({ label: displayName + ' · ' + email })
  await certificateAdmin.getByLabel('Huella SHA-256 pública').fill(certificate.fingerprint)
  await certificateAdmin.getByLabel('Referencia de comprobación de identidad').fill('Comprobación de certificado público generado para E2E.')
  await certificateAdmin.getByLabel('He comprobado que el certificado público corresponde a esta cuenta.').check()
  await certificateAdmin.getByRole('button', { name: 'Vincular huella pública', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Huella pública vinculada.' })).toHaveText('Huella pública vinculada.')

  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await page.getByRole('textbox', { name: 'Usuario', exact: true }).fill(email)
  await page.getByLabel('Contraseña', { exact: true }).fill('E2e-only-temporary-password')
  await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Acceso temporal' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Administración', exact: true })).toHaveCount(0)
  await page.getByLabel('Contraseña actual').fill('E2e-only-temporary-password')
  await page.getByLabel('Nueva contraseña', { exact: true }).fill(userPassword)
  await page.getByLabel('Confirmar contraseña').fill(userPassword)
  await page.getByRole('button', { name: 'Guardar contraseña' }).click()
  await page.getByRole('textbox', { name: 'Usuario', exact: true }).fill(email)
  await page.getByLabel('Contraseña', { exact: true }).fill(userPassword)
  await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Bienvenido, ' + displayName })).toBeVisible()
  await page.getByLabel('Contexto de grupo').selectOption({ label: group })
  await expect(page.getByText(displayName + ' · Miembro', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Bienvenido, ' + displayName })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await page.getByRole('button', { name: '¿Olvidó su contraseña?' }).click()
  await page.getByLabel('Correo institucional').fill(email)
  await page.getByRole('button', { name: 'Enviar enlace' }).click()
  await expect(page.getByRole('status')).toContainText('Si el correo está registrado')
  await expect.poll(async () => {
    const result = await (await request.get((process.env.E2E_MAIL_URL || 'http://127.0.0.1:18025') + '/api/v1/messages')).json()
    return result.messages.some((m: { To: { Address: string }[] }) => m.To.some(to => to.Address === email))
  }).toBeTruthy()
  const messages = await (await request.get((process.env.E2E_MAIL_URL || 'http://127.0.0.1:18025') + '/api/v1/messages')).json()
  const message = messages.messages.find((m: { To: { Address: string }[] }) => m.To.some(to => to.Address === email))
  expect(message).toBeTruthy()
  const detail = await (await request.get((process.env.E2E_MAIL_URL || 'http://127.0.0.1:18025') + '/api/v1/message/' + message.ID)).json()
  const link = String(detail.Text).match(/http[^\s]+#reset=[^\s]+/)![0]
  const recovery = new URL(link)
  await page.goto('/' + recovery.hash)
  await page.getByLabel('Nueva contraseña', { exact: true }).fill('E2e-only-recovered-password')
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill('E2e-only-recovered-password')
  await page.getByRole('button', { name: 'Guardar contraseña' }).click()
  await expect(page.getByRole('status')).toContainText('Contraseña actualizada')
  await page.getByRole('textbox', { name: 'Usuario', exact: true }).fill(email)
  await page.getByLabel('Contraseña', { exact: true }).fill('E2e-only-recovered-password')
  await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Bienvenido, ' + displayName })).toBeVisible()
  await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/home-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Documentos', exact: true }).click()
  await page.getByLabel('Título del nuevo Plan').fill('Plan E2E ' + suffix)
  await page.getByLabel('Grupo del nuevo Plan').selectOption({ label: group })
  await page.getByLabel('Período del nuevo Plan').selectOption({ label: 'Período ' + suffix })
  await page.getByRole('button', { name: 'Crear borrador' }).click()
  await expect(page.getByLabel('Título del Plan', { exact: true })).toHaveValue('Plan E2E ' + suffix)
  await page.getByLabel('Unidad institucional').fill('FISEI')
  await page.getByRole('button', { name: 'Contenido', exact: true }).click()
  await page.getByLabel('Justificación').fill('Contenido real guardado en PostgreSQL')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'Inicio', exact: true }).click()
  await expect(page.getByLabel('Justificación')).toHaveValue('Contenido real guardado en PostgreSQL')
  await page.getByRole('button', { name: 'Guardar borrador', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Borrador guardado' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Documentos', exact: true }).click()
  await page.getByRole('button', { name: 'Editar Plan E2E ' + suffix, exact: true }).click()
  await page.getByRole('button', { name: 'Contenido', exact: true }).click()
  await expect(page.getByLabel('Justificación')).toHaveValue('Contenido real guardado en PostgreSQL')
  const other = await page.context().newPage()
  await other.goto('/')
  await other.getByRole('button', { name: 'Documentos', exact: true }).click()
  await other.getByRole('button', { name: 'Editar Plan E2E ' + suffix, exact: true }).click()
  await other.getByLabel('Unidad institucional').fill('Unidad actualizada')
  await other.getByRole('button', { name: 'Guardar borrador', exact: true }).click()
  await expect(other.getByRole('status').filter({ hasText: 'Borrador guardado' })).toBeVisible()
  await page.getByLabel('Justificación').fill('Cambios locales conservados')
  await page.getByRole('button', { name: 'Guardar borrador', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('cambió en otra sesión')
  await expect(page.getByLabel('Justificación')).toHaveValue('Cambios locales conservados')
  await page.getByRole('button', { name: 'Consultar versión actual' }).click()
  await expect(page.getByText('Unidad actualizada', { exact: true })).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Descartar cambios y cargar versión actual' }).click()
  await expect(page.getByLabel('Justificación')).toHaveValue('Contenido real guardado en PostgreSQL')

  await page.getByRole('button', { name: 'Actividades y matriz', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Actividades y matriz T1', exact: true })).toBeVisible()
  const requiredActivity = page.getByRole('region', { name: 'Actividad 1', exact: true })
  await expect(requiredActivity.getByRole('button', { name: /Quitar/ })).toHaveCount(0)
  const activityDate = new Date().toISOString().slice(0,10)
  await requiredActivity.getByLabel('Desde', { exact: true }).fill(activityDate)
  await requiredActivity.getByLabel('Hasta', { exact: true }).fill(activityDate)
  await requiredActivity.getByRole('button', { name: 'Seleccionar todos' }).click()
  await requiredActivity.getByLabel('Usar denominación colectiva', { exact: false }).check()
  await requiredActivity.getByLabel('Recurso E2E ' + suffix, { exact: true }).check()
  await requiredActivity.getByLabel('Medio E2E ' + suffix, { exact: true }).check()
  await requiredActivity.getByRole('group', { name: 'Recursos', exact: true }).getByLabel('Otro', { exact: true }).check()
  await page.getByRole('button', { name: 'Guardar matriz', exact: true }).click()
  await expect(page.getByText('Escriba una descripción.', { exact: true })).toBeVisible()
  await expect(requiredActivity.getByLabel('Descripción de Otro (Recursos)', { exact: true })).toBeFocused()
  await requiredActivity.getByLabel('Descripción de Otro (Recursos)', { exact: true }).fill('Recurso adicional')
  await page.getByLabel('Fuente de la matriz').fill('Planificación del grupo')
  await page.getByRole('button', { name: 'Guardar matriz', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Matriz guardada' })).toBeVisible()
  await page.getByLabel('Título de Otra actividad').fill('Actividad libre E2E')
  await page.getByRole('button', { name: 'Agregar actividad', exact: true }).click()
  const customActivity = page.getByRole('region', { name: 'Actividad 2', exact: true })
  await customActivity.getByLabel('Desde', { exact: true }).fill(activityDate)
  await customActivity.getByLabel('Hasta', { exact: true }).fill(activityDate)
  await customActivity.getByRole('button', { name: 'Seleccionar todos' }).click()
  await customActivity.getByLabel('Recurso E2E ' + suffix, { exact: true }).check()
  await customActivity.getByLabel('Medio E2E ' + suffix, { exact: true }).check()
  await page.getByRole('button', { name: 'Guardar matriz', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Matriz guardada' })).toBeVisible()
  await page.getByRole('button', { name: 'Volver al Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Actividades y matriz', exact: true }).click()
  await expect(page.getByLabel('Fuente de la matriz')).toHaveValue('Planificación del grupo')
  await expect(page.getByRole('region', { name: 'Actividad 2', exact: true }).getByRole('heading', { name: '2. Actividad libre E2E', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Actividad 1', exact: true }).getByLabel('Descripción de Otro (Recursos)', { exact: true })).toHaveValue('Recurso adicional')

  await other.goto('/')
  await other.getByRole('button', { name: 'Documentos', exact: true }).click()
  await other.getByRole('button', { name: 'Editar Plan E2E ' + suffix, exact: true }).click()
  await other.getByRole('button', { name: 'Actividades y matriz', exact: true }).click()
  await other.getByLabel('Fuente de la matriz').fill('Fuente actualizada en otra pestaña')
  await other.getByRole('button', { name: 'Guardar matriz', exact: true }).click()
  await expect(other.getByRole('status').filter({ hasText: 'Matriz guardada' })).toBeVisible()
  await page.getByLabel('Fuente de la matriz').fill('Cambios locales de matriz')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'Inicio', exact: true }).click()
  await expect(page.getByLabel('Fuente de la matriz')).toHaveValue('Cambios locales de matriz')
  await page.getByRole('button', { name: 'Guardar matriz', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('cambió en otra sesión')
  await expect(page.getByLabel('Fuente de la matriz')).toHaveValue('Cambios locales de matriz')
  await page.getByRole('button', { name: 'Consultar matriz actual', exact: true }).click()
  await expect(page.getByText('Fuente: Fuente actualizada en otra pestaña', { exact: true })).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Descartar cambios y cargar matriz actual', exact: true }).click()
  await expect(page.getByLabel('Fuente de la matriz')).toHaveValue('Fuente actualizada en otra pestaña')
  await page.getByRole('heading', { name: 'Actividades y matriz T1', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/matrix-mobile.png' })
  await page.getByRole('heading', { name: 'Resumen de la matriz', exact: true }).locator('..').screenshot({ path: 'test-results/matrix-summary-mobile.png' })

  await page.screenshot({ path: 'test-results/work-plan-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Volver al Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Preparación y previsualización', exact: true }).click()
  await expect(page.getByText('Complete el objetivo.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Generar previsualización', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Volver al Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Contenido', exact: true }).click()
  await page.getByLabel('Objetivo', { exact: true }).fill('Cumplir la planificación y documentar los resultados.')
  await page.getByRole('button', { name: 'Guardar borrador', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Borrador guardado' })).toBeVisible()
  await page.getByRole('button', { name: 'Anexos y opciones', exact: true }).click()
  await page.getByLabel('¿El Plan tiene anexos?').selectOption('true')
  await expect(page.getByLabel('Título del anexo', { exact: true })).toBeVisible()
  await page.getByLabel('Título del anexo', { exact: true }).fill('Acta original E2E')
  await page.getByLabel('Archivo PDF del anexo').setInputFiles({ name: 'acta.pdf', mimeType: 'application/pdf', buffer: annexPdf() })
  await page.getByRole('button', { name: 'Agregar PDF', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Anexo A. Acta original E2E', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Editar Anexo A', exact: true }).click()
  await page.getByLabel('Descripción del anexo').fill('Descripción persistida del anexo.')
  await page.getByRole('button', { name: 'Guardar anexo', exact: true }).click()
  await expect(page.getByText('Descripción persistida del anexo.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Volver al Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Preparación y previsualización', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Listo para generar' })).toBeVisible()
  await page.getByRole('button', { name: 'Generar previsualización', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Descargar PDF T1' })).toBeVisible({ timeout: 90000 })
  const signature = page.getByRole('region', { name: 'Preparación de firma', exact: true })
  await expect(signature.getByText('Este artefacto no contiene una revisión de flujo configurada.', { exact: true })).toBeVisible()
  await expect(signature.getByText('Pendiente confirmar etapas, participantes', { exact: false })).toBeVisible()
  await expect(signature.getByText('Pendiente definir vinculación certificado', { exact: false })).toBeVisible()
  expect(await signature.locator('input[type="file"], input[type="password"]').count()).toBe(0)
  const signatureArtifactUrl = (await page.getByRole('link', { name: 'Descargar PDF T1' }).getAttribute('href'))!.replace('/content', '/signature-preparation')
  const signatureResponse = await page.request.get(signatureArtifactUrl)
  expect(signatureResponse.headers()['cache-control']).toContain('no-store')
  expect((await signatureResponse.json()).signingEnabled).toBe(false)
  await signature.getByRole('button', { name: 'Actualizar preparación de firma', exact: true }).click()
  await expect(signature.getByText('Integridad del PDF almacenado comprobada.', { exact: false })).toBeVisible()
  await signature.screenshot({ path: 'test-results/signature-preparation-mobile.png' })
  const authorSigning = page.getByRole('region', { name: 'Firma del elaborador', exact: true })
  await expect(authorSigning.getByRole('button', { name: 'Firmar', exact: true })).toBeEnabled()
  await authorSigning.getByLabel('Certificado personal (.p12/.pfx)').setInputFiles({ name: 'personal.p12', mimeType: 'application/x-pkcs12', buffer: certificate.buffer })
  await authorSigning.getByLabel('Contraseña del certificado', { exact: true }).fill('Wrong-test-password')
  await authorSigning.getByRole('button', { name: 'Firmar', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(authorSigning.getByLabel('Contraseña del certificado', { exact: true })).toHaveValue('')
  await expect(authorSigning.getByLabel('Certificado personal (.p12/.pfx)')).toHaveValue('')
  await authorSigning.getByLabel('Certificado personal (.p12/.pfx)').setInputFiles({ name: 'personal.pfx', mimeType: 'application/x-pkcs12', buffer: certificate.buffer })
  await authorSigning.getByLabel('Contraseña del certificado', { exact: true }).fill(certificate.password)
  await authorSigning.getByRole('button', { name: 'Firmar', exact: true }).click()
  await expect(authorSigning.getByRole('link', { name: 'Descargar PDF firmado' })).toBeVisible({ timeout: 30000 })
  await expect(authorSigning.locator('input[type="file"], input[type="password"]')).toHaveCount(0)
  await expect(authorSigning.getByText('La cadena de la entidad emisora y la revocación no fueron comprobadas.', { exact: false })).toBeVisible()
  await expect.poll(() => authorSigning.getByRole('img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBeTruthy()
  const signedLink = await authorSigning.getByRole('link', { name: 'Descargar PDF firmado' }).getAttribute('href')
  const signedBytes = await (await page.request.get(signedLink!)).body()
  await authorSigning.screenshot({ path: 'test-results/author-signature-mobile.png' })
  await expect.poll(() => page.getByAltText('Página 1 del Plan T1').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBeTruthy()
  const pdfLink = await page.getByRole('link', { name: 'Descargar PDF T1' }).getAttribute('href')
  const original = await (await page.request.get(pdfLink!)).body()
  expect(original.subarray(0,5).toString()).toBe('%PDF-')
  await page.getByRole('button', { name: 'Página siguiente', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Página 2 de' })).toBeVisible()
  await expect.poll(() => page.getByAltText('Página 2 del Plan T1').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBeTruthy()
  await page.screenshot({ path: 'test-results/t1-preview-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: 'test-results/t1-preview-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Volver al Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Anexos y opciones', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Quitar Anexo A', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Anexo A. Acta original E2E', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Volver al Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Preparación y previsualización', exact: true }).click()
  await expect(page.getByText('Previsualización anterior:', { exact: false })).toBeVisible()
  await expect(signature.getByText('Artefacto anterior: vuelva a generar la previsualización.', { exact: false })).toBeVisible()
  expect((await (await page.request.get(signatureArtifactUrl)).json()).artifactCurrent).toBe(false)
  expect(await (await page.request.get(pdfLink!)).body()).toEqual(original)
  expect(await (await page.request.get(signedLink!)).body()).toEqual(signedBytes)
  await page.getByRole('button', { name: 'Volver al Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Historial del Plan', exact: true }).click()
  const history = page.getByRole('region', { name: 'Historial del Plan', exact: true })
  await expect(history.getByRole('cell', { name: 'Previsualización T1 generada' })).toBeVisible()
  await expect(history.getByRole('cell', { name: 'Anexo retirado' })).toBeVisible()
  await expect(history.getByRole('cell', { name: 'Plan creado' })).toBeVisible()
  await expect(history.getByRole('cell', { name: 'Sesión iniciada' })).toHaveCount(0)
  await history.screenshot({ path: 'test-results/document-history-mobile.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await other.close()
  await page.getByRole('button', { name: 'Inicio', exact: true }).click()
  const tracking = page.getByRole('region', { name: 'Seguimiento de mis documentos', exact: true })
  await expect(tracking.getByText('Documentos disponibles', { exact: true })).toBeVisible()
  await expect(tracking.getByText('Documentos de solo lectura', { exact: true })).toBeVisible()
  await tracking.screenshot({ path: 'test-results/tracking-mobile.png' })
  await tracking.getByRole('button', { name: /^Abrir desde seguimiento:/ }).first().click()
  await expect(page.getByRole('button', { name: 'Historial del Plan', exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: 'Notificaciones', exact: true }).click()
  const notifications = page.getByRole('region', { name: 'Bandeja de notificaciones', exact: true })
  await expect(notifications.getByRole('heading', { name: 'Previsualización T1 guardada', exact: true })).toBeVisible()
  certificate.buffer.fill(0)
  await notifications.screenshot({ path: 'test-results/notifications-mobile.png' })
  const previewNotice = notifications.getByRole('listitem', { name: 'Previsualización T1 guardada', exact: true })
  await previewNotice.getByRole('button', { name: 'Abrir objeto', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Plan E2E ' + suffix, exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: 'Notificaciones', exact: true }).click()
  await notifications.getByRole('button', { name: 'Marcar todas como leídas', exact: true }).click()
  await notifications.getByLabel('Estado de lectura', { exact: true }).selectOption('false')
  await expect(notifications.getByText('No hay notificaciones para este filtro.', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: 'Notificaciones', exact: true }).click()
  await notifications.getByLabel('Estado de lectura', { exact: true }).selectOption('true')
  await expect(notifications.getByRole('heading', { name: 'Previsualización T1 guardada', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Inicio', exact: true }).click()
  await page.getByLabel('Contexto de grupo').selectOption({ label: group })
  await expect(page.getByText(displayName + ' · Miembro', { exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: 'Notificaciones', exact: true }).click()
  await page.getByRole('listitem', { name: 'Pertenencia actualizada', exact: true }).getByRole('button', { name: 'Abrir objeto', exact: true }).click()
  await expect(page.getByLabel('Contexto de grupo').locator('option:checked')).toHaveText(group)
  await expect(page.getByText(displayName + ' · Miembro', { exact: true })).toBeVisible()

})
