import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

const environment = Object.fromEntries(readFileSync('../.env.e2e', 'utf8').split(/\r?\n/).filter(s => s.includes('=')).map(s => { const i = s.indexOf('='); return [s.slice(0, i), s.slice(i + 1)] }))
test('versioned workflows preserve history and require explicit recipients', async ({ page, request }) => {
  test.setTimeout(120000)
  await expect.poll(async () => { try { return (await request.get('http://127.0.0.1:18080/actuator/health')).status() } catch { return 0 } }, { timeout: 30000 }).toBe(200)
  await page.goto('/')
  await page.getByLabel('Correo institucional').fill(environment.BOOTSTRAP_ADMIN_EMAIL)
  await page.getByLabel('Contraseña', { exact: true }).fill(environment.BOOTSTRAP_ADMIN_PASSWORD)
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect.poll(async () => await page.getByRole('alert').isVisible() || await page.getByRole('button', { name: 'Cerrar sesión' }).isVisible()).toBeTruthy()
  if (await page.getByRole('alert').isVisible()) { await page.getByLabel('Contraseña', { exact: true }).fill('E2e-only-admin-password-2026'); await page.getByRole('button', { name: 'Ingresar', exact: true }).click() }
  await expect(page.getByRole('button', { name: 'Cerrar sesión' })).toBeVisible()
  if (await page.getByRole('heading', { name: 'Cambie su contraseña temporal' }).isVisible()) {
    await page.getByLabel('Contraseña actual').fill(environment.BOOTSTRAP_ADMIN_PASSWORD)
    await page.getByLabel('Nueva contraseña', { exact: true }).fill('E2e-only-admin-password-2026')
    await page.getByLabel('Confirmar contraseña').fill('E2e-only-admin-password-2026')
    await page.getByRole('button', { name: 'Guardar contraseña' }).click()
    await expect(page.getByRole('heading', { name: 'Iniciar sesión' })).toBeVisible()
    await page.getByLabel('Correo institucional').fill(environment.BOOTSTRAP_ADMIN_EMAIL)
    await page.getByLabel('Contraseña', { exact: true }).fill('E2e-only-admin-password-2026')
    await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  }
  await page.getByRole('button', { name: 'Administración', exact: true }).click()
  const suffix = Date.now(); const group = 'Grupo de flujo ' + suffix; const person = 'Revisor de flujo ' + suffix
  await page.getByLabel('Nombre', { exact: true }).fill(person)
  await page.getByLabel('Correo', { exact: true }).fill('flow-' + suffix + '@example.invalid')
  await page.getByLabel('Contraseña temporal', { exact: true }).fill('E2e-only-temporary-password')
  await page.getByRole('button', { name: 'Crear usuario', exact: true }).click()
  await expect(page.getByRole('cell', { name: person, exact: true })).toBeVisible()
  await page.getByLabel('Nombre del grupo').fill(group)
  await page.getByRole('button', { name: 'Crear grupo', exact: true }).click()
  await expect(page.getByLabel('Grupo del flujo')).toContainText(group)
  await page.getByLabel('Grupo del flujo').selectOption({ label: group })
  await page.getByLabel('Nombre del flujo').fill('Flujo original ' + suffix)
  await page.getByRole('button', { name: 'Agregar etapa', exact: true }).click()
  const first = page.getByRole('region', { name: 'Etapa 1', exact: true })
  await first.getByLabel('Nombre de la etapa').fill('Revisión técnica')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'Inicio', exact: true }).click()
  await expect(first.getByLabel('Nombre de la etapa')).toHaveValue('Revisión técnica')
  await page.getByRole('button', { name: 'Guardar borrador del flujo', exact: true }).click()
  await expect(page.getByText('Revisión técnica: seleccione personas, sin rol ni órgano colegiado.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Guardar como configuración vigente', exact: true })).toBeDisabled()
  await first.getByLabel(person, { exact: true }).check()
  await page.getByRole('button', { name: 'Agregar etapa', exact: true }).click()
  const second = page.getByRole('region', { name: 'Etapa 2', exact: true })
  await second.getByLabel('Nombre de la etapa').fill('Decisión colegiada')
  await second.getByLabel('Acción de la etapa').selectOption('APPROVE')
  await second.getByLabel('Destinatario de la etapa').selectOption('COLLEGIATE')
  await second.getByLabel('Nombre del órgano colegiado').fill('Órgano configurado para prueba')
  await expect(second.getByRole('group', { name: 'Participantes de la etapa' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Guardar borrador del flujo', exact: true }).click()
  await page.getByRole('button', { name: 'Guardar como configuración vigente', exact: true }).click()
  await expect(page.getByText('Revisión de configuración vigente: 1', { exact: true })).toBeVisible()
  await page.getByLabel('Nombre del flujo').fill('Flujo cambiado ' + suffix)
  await page.getByRole('button', { name: 'Subir etapa 2', exact: true }).click()
  await page.getByRole('button', { name: 'Guardar borrador del flujo', exact: true }).click()
  await page.getByRole('button', { name: 'Guardar como configuración vigente', exact: true }).click()
  await expect(page.getByText('Revisión de configuración vigente: 2', { exact: true })).toBeVisible()
  await page.getByLabel('Historial de configuración').selectOption({ label: '1 · Flujo original ' + suffix })
  await expect(page.getByRole('heading', { name: 'Revisión 1: Flujo original ' + suffix, exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('heading', { name: 'Flujos por grupo', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/workflow-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Deshabilitar configuración', exact: true }).click()
  await expect(page.getByText('Sin configuración vigente.', { exact: true })).toBeVisible()
  await page.getByLabel('Tipo documental del flujo').selectOption('T2')
  await expect(page.getByLabel('Nombre del flujo')).toHaveValue('')
})
