import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { solveCaptcha } from './login'

const environment = Object.fromEntries(readFileSync('../.env.e2e', 'utf8').split(/\r?\n/).filter(line => line.includes('=')).map(line => { const i = line.indexOf('='); return [line.slice(0,i),line.slice(i+1)] }))

test('modern access preserves credentials, supports username and administrative password reset', async ({ page }) => {
  test.setTimeout(150000)
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Iniciar sesión', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/access-desktop.png', fullPage: true })
  await page.getByRole('textbox', { name: 'Usuario', exact: true }).fill(environment.BOOTSTRAP_ADMIN_EMAIL)
  await page.getByLabel('Contraseña', { exact: true }).fill('E2e-only-admin-password-2026')
  await solveCaptcha(page)
  await page.getByLabel('Código de verificación', { exact: true }).fill('ZZZ999')
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('código de verificación')
  await expect(page.getByRole('textbox', { name: 'Usuario', exact: true })).toHaveValue(environment.BOOTSTRAP_ADMIN_EMAIL)
  await expect(page.getByLabel('Contraseña', { exact: true })).toHaveValue('E2e-only-admin-password-2026')
  await expect(page.getByLabel('Código de verificación', { exact: true })).toHaveValue('')
  await page.getByRole('button', { name: 'Mostrar contraseña', exact: true }).click()
  await expect(page.getByLabel('Contraseña', { exact: true })).toHaveAttribute('type','text')
  await page.getByRole('button', { name: 'Ocultar contraseña', exact: true }).click()
  await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect.poll(async () => await page.getByRole('alert').isVisible() || await page.getByRole('button', { name: 'Cerrar sesión' }).isVisible()).toBeTruthy()
  if (await page.getByRole('alert').isVisible()) {
    await page.getByLabel('Contraseña', { exact: true }).fill(environment.BOOTSTRAP_ADMIN_PASSWORD)
    await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  }
  await expect(page.getByRole('button', { name: 'Cerrar sesión' })).toBeVisible()
  if (await page.getByRole('heading', { name: 'Cambie su contraseña temporal' }).isVisible()) {
    await page.getByLabel('Contraseña actual').fill(environment.BOOTSTRAP_ADMIN_PASSWORD)
    await page.getByLabel('Nueva contraseña', { exact: true }).fill('E2e-only-admin-password-2026')
    await page.getByLabel('Confirmar contraseña', { exact: true }).fill('E2e-only-admin-password-2026')
    await page.getByRole('button', { name: 'Guardar contraseña' }).click()
    await page.getByRole('textbox', { name: 'Usuario', exact: true }).fill(environment.BOOTSTRAP_ADMIN_EMAIL)
    await page.getByLabel('Contraseña', { exact: true }).fill('E2e-only-admin-password-2026')
    await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  }
  await expect(page.getByRole('navigation', { name: 'Navegación principal' })).toBeVisible()
  await page.getByRole('button', { name: 'Administración', exact: true }).click()
  const suffix = Date.now().toString(); const username = 'reset-' + suffix
  await page.getByLabel('Nombres', { exact: true }).fill('Cuenta')
  await page.getByLabel('Apellidos', { exact: true }).fill(suffix)
  await page.getByLabel('Correo', { exact: true }).fill(username + '@example.invalid')
  await page.getByLabel('Identificador de acceso', { exact: true }).fill(username)
  await page.getByLabel('Contraseña temporal', { exact: true }).fill('E2e-only-first-password')
  await page.getByRole('button', { name: 'Crear usuario', exact: true }).click()
  await page.getByRole('button', { name: 'Restablecer acceso de Cuenta ' + suffix, exact: true }).click()
  const reset = page.getByRole('region', { name: 'Restablecer acceso', exact: true })
  await expect(reset.getByLabel('Nueva contraseña temporal')).toBeFocused()
  await reset.getByLabel('Nueva contraseña temporal').fill('E2e-only-admin-reset-password')
  await reset.getByLabel('Confirmar contraseña temporal').fill('E2e-only-admin-reset-password')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'Inicio', exact: true }).click()
  await expect(reset.getByLabel('Nueva contraseña temporal')).toHaveValue('E2e-only-admin-reset-password')
  await reset.getByLabel('Confirmo el restablecimiento de esta cuenta.').check()
  let releaseRefresh = () => {}; let capturedRefresh = () => {}; let completedRefresh = () => {}
  const heldRefresh = new Promise<void>(resolve => { releaseRefresh = resolve })
  const captured = new Promise<void>(resolve => { capturedRefresh = resolve })
  const completed = new Promise<void>(resolve => { completedRefresh = resolve })
  await page.route('**/api/auth/me', async route => {
    const response = await route.fetch(); capturedRefresh(); await heldRefresh
    await route.fulfill({ response }); completedRefresh()
  })
  await reset.getByRole('button', { name: 'Restablecer contraseña', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Acceso restablecido.' })).toBeVisible()
  await captured
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await expect(page.getByRole('heading', { name: 'Iniciar sesión', exact: true })).toBeVisible()
  releaseRefresh(); await completed; await page.unroute('**/api/auth/me')
  await expect(page.getByRole('navigation', { name: 'Navegación principal' })).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Usuario', exact: true }).fill(username)
  await page.getByLabel('Contraseña', { exact: true }).fill('E2e-only-admin-reset-password')
  await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Cambie su contraseña temporal' })).toBeVisible()
  await page.getByLabel('Contraseña actual').fill('E2e-only-admin-reset-password')
  await page.getByLabel('Nueva contraseña', { exact: true }).fill('E2e-only-final-password-2026')
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill('E2e-only-final-password-2026')
  await page.getByRole('button', { name: 'Guardar contraseña' }).click()
  await page.getByRole('textbox', { name: 'Usuario', exact: true }).fill(username)
  await page.getByLabel('Contraseña', { exact: true }).fill('E2e-only-final-password-2026')
  await solveCaptcha(page); await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Bienvenido, Cuenta ' + suffix })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Administración', exact: true })).toHaveCount(0)
  for (const [name,width,height] of [['desktop',1440,1000],['tablet',820,1180],['mobile',390,844]] as const) {
    await page.setViewportSize({ width,height })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    await page.screenshot({ path: 'test-results/workspace-' + name + '.png', fullPage: true })
  }
  await page.getByRole('button', { name: 'Documentos', exact: true }).click()
  await expect(page.getByText('Necesita pertenecer a un grupo activo para crear un Plan. Solicite la asignación al administrador.')).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Ingresar', exact: true })).toBeEnabled()
  await page.screenshot({ path: 'test-results/access-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
})
