import { useEffect, useState } from 'react'
import { api, type Group, type User } from '../shared/api'
interface Stage { id: string; label: string; action: string; recipientKind: string; assigneeIds: string[]; groupRole: string | null; recipientLabel: string; requiresSignature: boolean }
interface Definition { name: string; stages: Stage[] }
interface Revision { id: string; revisionNumber: number; definition: Definition; configuredBy: string; configuredAt: string }
interface State { rowVersion: number; groupActive: boolean; draft: Definition; current: Revision | null; revisions: Revision[]; blockers: string[] }
export function WorkflowAdministration({ groups, users, onDirtyChange }: { groups: Group[]; users: User[]; onDirtyChange: (dirty: boolean) => void }) {
  const [group, setGroup] = useState(''); const [type, setType] = useState('T1'); const [state, setState] = useState<State | null>(null)
  const [draft, setDraft] = useState<Definition>({ name: '', stages: [] }); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const [revision, setRevision] = useState<Revision | null>(null)
  const path = '/admin/groups/' + group + '/workflows/' + type
  const dirty = state !== null && JSON.stringify(draft) !== JSON.stringify(state.draft)
  useEffect(() => { onDirtyChange(dirty); const prevent = (e: BeforeUnloadEvent) => { if (dirty) { e.preventDefault(); e.returnValue = '' } }; window.addEventListener('beforeunload', prevent); return () => { window.removeEventListener('beforeunload', prevent); onDirtyChange(false) } }, [dirty, onDirtyChange])
  useEffect(() => { let active = true; if (group) api<State>(path).then(s => { if (active) { setState(s); setDraft(s.draft); setRevision(null) } }).catch(e => { if (active) setError(e.message) }); return () => { active = false } }, [group, path])
  function choose(nextGroup: string, nextType: string) { if (!dirty || window.confirm('¿Descartar los cambios del flujo sin guardar?')) { setGroup(nextGroup); setType(nextType); setState(null); setError(''); setNotice(''); setRevision(null) } }
  function change(id: string, values: Partial<Stage>) { setDraft(d => ({ ...d, stages: d.stages.map(s => s.id === id ? { ...s, ...values } : s) })); setNotice('') }
  function move(index: number, delta: number) { setDraft(d => { const stages = [...d.stages]; [stages[index], stages[index + delta]] = [stages[index + delta], stages[index]]; return { ...d, stages } }) }
  async function operation(suffix: string, method: string, body?: unknown) {
    setBusy(true); setError(''); setNotice('')
    try { const saved = await api<State>(path + suffix, method, body); setState(saved); setDraft(saved.draft); setNotice('Configuración guardada.'); setRevision(null) }
    catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar el flujo.') } finally { setBusy(false) }
  }
  return <section className="card"><h3>Flujos por grupo</h3><p>Configure etapas y destinatarios de cada tipo documental. Las revisiones guardadas conservan su definición; esta configuración todavía no inicia revisión ni aplica firmas.</p>
    <div className="grid"><label>Grupo del flujo<select value={group} disabled={busy} onChange={e => choose(e.target.value, type)}><option value="">Seleccione</option>{groups.map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Tipo documental del flujo<select value={type} disabled={busy} onChange={e => choose(group, e.target.value)}><option value="T1">Plan T1</option><option value="T2">Informe T2</option></select></label></div>
    {error && <p className="error" role="alert">{error}</p>}{notice && <p className="notice" role="status">{notice}</p>}
    {group && !state && <p role="status">Cargando flujo…</p>}
    {state && <><p>{state.current ? 'Revisión de configuración vigente: ' + state.current.revisionNumber : 'Sin configuración vigente.'}</p>{!state.groupActive && <p>Grupo inactivo: configuración de solo lectura.</p>}
      <form onSubmit={e => { e.preventDefault(); void operation('', 'PUT', { rowVersion: state.rowVersion, definition: draft }) }}><fieldset disabled={busy || !state.groupActive}>
        <label>Nombre del flujo<input required maxLength={160} value={draft.name} onChange={e => setDraft(d => ({ ...d, name: e.target.value }))} /></label>
        {draft.stages.map((s, index) => <section className="card" key={s.id} aria-label={'Etapa ' + (index + 1)}><h4>Etapa {index + 1}</h4><label>Nombre de la etapa<input required maxLength={160} value={s.label} onChange={e => change(s.id, { label: e.target.value })} /></label>
          <label>Acción de la etapa<select value={s.action} onChange={e => change(s.id, { action: e.target.value })}><option value="REVIEW">Revisión</option><option value="VALIDATE">Validación</option><option value="APPROVE">Aprobación</option></select></label>
          <label>Destinatario de la etapa<select value={s.recipientKind} onChange={e => change(s.id, { recipientKind: e.target.value, assigneeIds: [], groupRole: e.target.value === 'GROUP_ROLE' ? 'COORDINATOR' : null, recipientLabel: '' })}><option value="PERSON">Personas</option><option value="GROUP_ROLE">Rol de pertenencia del grupo</option><option value="COLLEGIATE">Órgano colegiado</option></select></label>
          {s.recipientKind === 'COLLEGIATE' && <label>Nombre del órgano colegiado<input required maxLength={160} value={s.recipientLabel} onChange={e => change(s.id, { recipientLabel: e.target.value })} /></label>}
          {s.recipientKind === 'GROUP_ROLE' && <label>Rol destinatario<select value={s.groupRole ?? ''} onChange={e => change(s.id, { groupRole: e.target.value })}><option value="MEMBER">Miembros</option><option value="COORDINATOR">Coordinadores</option></select></label>}
          <label className="check"><input type="checkbox" checked={s.requiresSignature} onChange={e => change(s.id, { requiresSignature: e.target.checked, assigneeIds: s.recipientKind === 'COLLEGIATE' ? [] : s.assigneeIds })} />Requiere firma personal</label>
          {(s.recipientKind === 'PERSON' || s.recipientKind === 'COLLEGIATE' && s.requiresSignature) && <fieldset className="choice-group"><legend>Participantes de la etapa</legend><p>Seleccione personas; varias personas representan participantes de la misma etapa. El avance efectivo depende del flujo institucional.</p>{users.filter(u => u.active || s.assigneeIds.includes(u.id)).map(u => <label className="check" key={u.id}><input type="checkbox" checked={s.assigneeIds.includes(u.id)} onChange={e => change(s.id, { assigneeIds: e.target.checked ? [...s.assigneeIds, u.id] : s.assigneeIds.filter(id => id !== u.id) })} />{u.display_name}{!u.active && ' · Inactivo'}</label>)}{s.assigneeIds.filter(id => !users.some(u => u.id === id)).map(id => <p key={id}>Participante registrado: {id}</p>)}</fieldset>}
          <button className="secondary" type="button" title="Subir etapa" aria-label={'Subir etapa ' + (index + 1)} disabled={index === 0} onClick={() => move(index, -1)}>↑</button>{' '}<button className="secondary" type="button" title="Bajar etapa" aria-label={'Bajar etapa ' + (index + 1)} disabled={index + 1 === draft.stages.length} onClick={() => move(index, 1)}>↓</button>{' '}<button className="danger" type="button" title="Quitar etapa del borrador" aria-label={'Quitar etapa ' + (index + 1)} onClick={() => setDraft(d => ({ ...d, stages: d.stages.filter(a => a.id !== s.id) }))}>×</button>
        </section>)}
        <button type="button" className="secondary" disabled={draft.stages.length >= 20} onClick={() => setDraft(d => ({ ...d, stages: [...d.stages, { id: crypto.randomUUID(), label: '', action: 'REVIEW', recipientKind: 'PERSON', assigneeIds: [], groupRole: null, recipientLabel: '', requiresSignature: false }] }))}>Agregar etapa</button>{' '}<button disabled={!dirty}>Guardar borrador del flujo</button>
      </fieldset></form>
      {state.blockers.length > 0 && <ul>{state.blockers.map((b, i) => <li key={i}>{b}</li>)}</ul>}
      <button disabled={busy || dirty || !state.groupActive || state.blockers.length > 0} onClick={() => void operation('/revisions', 'POST', { rowVersion: state.rowVersion })}>Guardar como configuración vigente</button>{' '}<button className="secondary" disabled={busy || dirty || !state.groupActive || !state.current} onClick={() => { if (window.confirm('¿Deshabilitar la configuración vigente conservando su historial?')) void operation('/disable', 'POST', { rowVersion: state.rowVersion }) }}>Deshabilitar configuración</button>{' '}<button className="secondary" disabled={busy} onClick={() => { if (!dirty || window.confirm('¿Descartar los cambios locales y recargar?')) void operation('', 'GET') }}>Recargar flujo</button>
      {state.revisions.length > 0 && <label>Historial de configuración<select value={revision?.id ?? ''} onChange={e => setRevision(state.revisions.find(r => r.id === e.target.value) ?? null)}><option value="">Seleccione revisión</option>{state.revisions.map(r => <option key={r.id} value={r.id}>{r.revisionNumber} · {r.definition.name}</option>)}</select></label>}
      {revision && <article><h4>Revisión {revision.revisionNumber}: {revision.definition.name}</h4><p>{revision.configuredBy} · {new Date(revision.configuredAt).toLocaleString('es-EC')}</p><ol>{revision.definition.stages.map(s => <li key={s.id}>{s.label} · {s.recipientLabel || s.groupRole || s.assigneeIds.map(id => users.find(u => u.id === id)?.display_name ?? id).join(', ')} · {s.requiresSignature ? 'Firma personal requerida' : 'Sin firma personal'}</li>)}</ol></article>}
    </>}
  </section>
}
